// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceregistry.proto

package binout.registry;

public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binout.registry.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
