// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serviceregistry.proto
// Protobuf Java Version: 4.29.3

package binout.registry;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binout.registry.Empty)
    com.google.protobuf.MessageOrBuilder {
}
