// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceregistry.proto

package binout.registry;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binout.registry.Empty)
    com.google.protobuf.MessageOrBuilder {
}
