// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceregistry.proto

package binout.registry;

public final class ServiceRegistryProto {
  private ServiceRegistryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_binout_registry_ServiceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_binout_registry_ServiceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_binout_registry_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_binout_registry_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_binout_registry_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_binout_registry_Ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_binout_registry_ServiceQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_binout_registry_ServiceQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_binout_registry_ServiceList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_binout_registry_ServiceList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025serviceregistry.proto\022\017binout.registry" +
      "\"O\n\013ServiceInfo\022\023\n\013serviceName\030\001 \001(\t\022\026\n\016" +
      "serviceAddress\030\002 \001(\t\022\023\n\013servicePort\030\003 \001(" +
      "\005\"\007\n\005Empty\"\'\n\003Ack\022\017\n\007success\030\001 \001(\010\022\017\n\007me" +
      "ssage\030\002 \001(\t\"#\n\014ServiceQuery\022\023\n\013serviceNa" +
      "me\030\001 \001(\t\"=\n\013ServiceList\022.\n\010services\030\001 \003(" +
      "\0132\034.binout.registry.ServiceInfo2\232\001\n\017Serv" +
      "iceRegistry\022>\n\010Register\022\034.binout.registr" +
      "y.ServiceInfo\032\024.binout.registry.Ack\022G\n\010D" +
      "iscover\022\035.binout.registry.ServiceQuery\032\034" +
      ".binout.registry.ServiceListB)\n\017binout.r" +
      "egistryB\024ServiceRegistryProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_binout_registry_ServiceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_binout_registry_ServiceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_binout_registry_ServiceInfo_descriptor,
        new java.lang.String[] { "ServiceName", "ServiceAddress", "ServicePort", });
    internal_static_binout_registry_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_binout_registry_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_binout_registry_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_binout_registry_Ack_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_binout_registry_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_binout_registry_Ack_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_binout_registry_ServiceQuery_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_binout_registry_ServiceQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_binout_registry_ServiceQuery_descriptor,
        new java.lang.String[] { "ServiceName", });
    internal_static_binout_registry_ServiceList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_binout_registry_ServiceList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_binout_registry_ServiceList_descriptor,
        new java.lang.String[] { "Services", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
