// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serviceregistry.proto
// Protobuf Java Version: 4.29.3

package binout.registry;

public interface ServiceListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binout.registry.ServiceList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .binout.registry.ServiceInfo services = 1;</code>
   */
  java.util.List<binout.registry.ServiceInfo> 
      getServicesList();
  /**
   * <code>repeated .binout.registry.ServiceInfo services = 1;</code>
   */
  binout.registry.ServiceInfo getServices(int index);
  /**
   * <code>repeated .binout.registry.ServiceInfo services = 1;</code>
   */
  int getServicesCount();
  /**
   * <code>repeated .binout.registry.ServiceInfo services = 1;</code>
   */
  java.util.List<? extends binout.registry.ServiceInfoOrBuilder> 
      getServicesOrBuilderList();
  /**
   * <code>repeated .binout.registry.ServiceInfo services = 1;</code>
   */
  binout.registry.ServiceInfoOrBuilder getServicesOrBuilder(
      int index);
}
