// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serviceregistry.proto
// Protobuf Java Version: 4.29.3

package binout.registry;

public interface ServiceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binout.registry.ServiceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceName = 1;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 1;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string serviceAddress = 2;</code>
   * @return The serviceAddress.
   */
  java.lang.String getServiceAddress();
  /**
   * <code>string serviceAddress = 2;</code>
   * @return The bytes for serviceAddress.
   */
  com.google.protobuf.ByteString
      getServiceAddressBytes();

  /**
   * <code>int32 servicePort = 3;</code>
   * @return The servicePort.
   */
  int getServicePort();
}
