// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: serviceregistry.proto
// Protobuf Java Version: 4.29.3

package binout.registry;

public interface ServiceQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binout.registry.ServiceQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceName = 1;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 1;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();
}
